### ISSUE TITLE
Quede o README jovem?

### ISSUE THREAD

**Issue by leandrooriente** [koz/map-project#1]
B A BA de como executar o projeto localmente 😉

**Comment by koz** [comment]
Falei com a @luizabreier sobre isso mais cedo, vou fazer hoje. Vou detalhar o roadmap nele também.

**Comment by koz** [comment]
Resolvido em 8bcb94f503139a8cf255ad51600f4b82fdc3e438

**Comment by leandrooriente** [comment]
`The guide for iOS setup is coming soon, just like winter.`

😆

**Comment by koz** [comment]
Vou fazer um contador desse aqui: http://www.theverge.com/2017/3/9/14872076/game-of-thrones-hbo-premiere-facebook-live-ice-block-what-is-going-on

**Comment by leandrooriente** [comment]
Hahaha, do caralho
